export const fmtNum = (n = 0) => {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + 'M'
  if (n >= 1_000)     return (n / 1_000).toFixed(1) + 'k'
  return String(n)
}

export const fmtDate = (iso) =>
  new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'short' })

export const yearFrom = (iso) => new Date(iso).getFullYear()

export const LANG_SHADES = {
  JavaScript: '#d8d8d0', TypeScript: '#b8b8b0', Python: '#a8a8a0',
  Rust:       '#c0c0b8', Go:         '#c8c8c0', 'C++': '#909088',
  C:          '#808078', Java:       '#a0a098', Ruby: '#989090',
  Swift:      '#b0a8a0', Kotlin:     '#888090', Shell: '#606058',
  HTML:       '#c0b8b0', CSS:        '#a8a0a0', Vue:  '#b0b8b0',
  PHP:        '#9898a0', Dart:       '#b0b8c0', Other: '#484840',
}

export const getLangColor = (lang) => LANG_SHADES[lang] ?? LANG_SHADES.Other

export const buildReadme = (user, repos) => {
  const top = [...repos].sort((a, b) => b.stargazers_count - a.stargazers_count).slice(0, 4)
  const repoCards = top.map(r =>
    `[![${r.name}](https://github-readme-stats.vercel.app/api/pin/?username=${user.login}&repo=${r.name}&theme=dark&bg_color=0a0a0a&border_color=222222&title_color=e8e8e0&text_color=888888&icon_color=666666)](https://github.com/${r.full_name})`
  ).join('\n')

  return `<!-- Nothing-style GitHub README — generated by nothing-github-stats -->

<div align="center">

\`\`\`
┌──────────────────────────────────────────────┐
│  ${(user.name || user.login).toUpperCase().padEnd(44)}│
│  @${user.login.padEnd(43)}│
│  ${(user.bio || '').substring(0, 44).padEnd(44)}│
└──────────────────────────────────────────────┘
\`\`\`

</div>

---

<img src="${user.avatar_url}" width="80" align="right" style="filter:grayscale(1);border:1px solid #222" />

**${user.name || user.login}**
${user.bio ? user.bio + '\n' : ''}${user.location ? `\`📍 ${user.location}\`\n` : ''}
\`repos: ${user.public_repos}\` · \`followers: ${fmtNum(user.followers)}\` · \`stars: ${fmtNum(repos.reduce((s, r) => s + r.stargazers_count, 0))}\`

---

### // stats

![GitHub Stats](https://github-readme-stats.vercel.app/api?username=${user.login}&show_icons=true&count_private=true&theme=dark&bg_color=0a0a0a&border_color=222222&title_color=e8e8e0&text_color=888888&icon_color=666666)

![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=${user.login}&layout=compact&theme=dark&bg_color=0a0a0a&border_color=222222&title_color=e8e8e0&text_color=888888)

![Streak](https://streak-stats.demolab.com?user=${user.login}&theme=dark&background=0a0a0a&border=222222&ring=e8e8e0&fire=e8e8e0&currStreakLabel=e8e8e0&sideLabels=666666&dates=444444)

---

### // contributions — snake

![Snake](https://raw.githubusercontent.com/${user.login}/${user.login}/output/github-contribution-grid-snake-dark.svg)

---

### // pinned

${repoCards}

---

<div align="center">
<sub><code>// built with nothing · monochrome · precise</code></sub>
</div>`
}
